version: '{build}'
image: Visual Studio 2017
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://piccolo.link/sbt-1.2.8.zip',
          'C:\sbt-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - cmd: SET PATH=C:\sbt\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g
build_script:
  - sbt "-Djna.nosys=true" ";clean; compile; test"
cache:
  - C:\Users\appveyor\.m2
  - C:\Users\appveyor\.ivy2
